name: Run AutoML Benchmark

on:
  workflow_dispatch:
    inputs:
      python_version:
        description: 'Python version'
        default: '3.9'
      os:
        description: 'OS to run on'
        default: 'ubuntu-latest'
      fedot_branch:
        description: 'FEDOT branch to test'
        default: 'master'
      framework:
        description: 'Framework to benchmark'
        default: 'FEDOT'
      benchmark_options:
        description: 'Additional benchmark options'
        default: ''

jobs:
  run_benchmark:
    runs-on: ${{ inputs.os }}

    steps:
      # Checkout automlbenchmark repo
      - name: Checkout automlbenchmark
        uses: actions/checkout@v3
        with:
          repository: openml/automlbenchmark
          path: automlbenchmark

      # Checkout FEDOT repo (specific branch)
      - name: Checkout FEDOT (${{ inputs.fedot_branch }})
        uses: actions/checkout@v3
        with:
          repository: aimclub/FEDOT
          ref: ${{ inputs.fedot_branch }}
          path: FEDOT

      # Setup Python
      - name: Set up Python ${{ inputs.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}

      # Install FEDOT in editable mode from the checked out branch
      - name: Install FEDOT from branch
        run: |
          pip install -e ./FEDOT

      # Install benchmark dependencies
      - name: Install benchmark dependencies
        working-directory: ./automlbenchmark
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run benchmark
      - name: Run benchmark for ${{ inputs.framework }}
        working-directory: ./automlbenchmark
        run: python runbenchmark.py ${{ inputs.framework }} ${{ inputs.benchmark_options }}
        env:
          GITHUB_PAT: ${{ secrets.PUBLIC_ACCESS_GITHUB_PAT }}