name: Integration (Core)

on:
  schedule:
    - cron: '0 12 * * *'
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest
    timeout-minutes: 95
    strategy:
      matrix:
        python-version: [ '3.10' ]

    steps:
      - name: Free disk space
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc

      - name: Checkout branch
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python pin ${{ matrix.python-version }}

      - name: Sync FEDOT dependencies
        run: |
          uv sync --group extra --group examples --group profilers --dev

      - name: FEDOT Integration tests
        run: |
          uv run pytest --cov=fedot -s test/integration

      - name: Notify telegram bot (schedule failure only)
        uses: appleboy/telegram-action@master
        if: ${{ failure() && github.event_name == 'schedule' }}
        with:
          to: ${{ secrets.CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "${{ github.event.repository.name }}: scheduled integration tests 
          [were failed](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})."
          format: markdown
          disable_web_page_preview: true
