name: Retrieval Integration

on:
  issue_comment:
    types: [created]

jobs:
  scheduled:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/retrieve_troubled_pipelines')
    timeout-minutes: 95
    strategy:
      matrix:
        python-version: [ 3.8, 3.9, '3.10' ]

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install .[extra]
          pip install .[examples]
          pip install .[profilers]
          pip install pytest-cov
      - name: Test with pytest
        run: |
          pytest --cov=fedot -s test/integration
      - name: Save pipelines
        uses: actions/upload-artifact@v3
        with:
          name: pipelines
          path: .invalid_fitness_after_evaluation/
