name: Mirror repo to GitLab

on: [push, delete]

jobs:
  call-nss-ops-mirror-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror commit (try-1)
        id: mirror-1
        uses: ITMO-NSS-team/NSS-Ops/.github/workflows/mirror-repo.yml@master
        continue-on-error: true
        with:
          GITLAB_URL: 'https://gitlab.actcognitive.org/itmo-nss-team/FEDOT.git'
        secrets:
          GITLAB_USER: ${{ secrets.GITLAB_USER }}
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
          
      - name: Sleep for 15 seconds
        run: sleep 15s
        shell: bash
          
      - name: Mirror commit (try-2)
        id: mirror-2
        uses: ITMO-NSS-team/NSS-Ops/.github/workflows/mirror-repo.yml@master
        continue-on-error: true
        with:
          GITLAB_URL: 'https://gitlab.actcognitive.org/itmo-nss-team/FEDOT.git'
        secrets:
          GITLAB_USER: ${{ secrets.GITLAB_USER }}
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        if: ${{ steps.mirror-1.outcome == 'failure' }}
        
      - name: Sleep for 15 seconds
        run: sleep 15s
        shell: bash
        
      - name: Mirror commit (try-3)
        id: mirror-3
        uses: ITMO-NSS-team/NSS-Ops/.github/workflows/mirror-repo.yml@master
        with:
          GITLAB_URL: 'https://gitlab.actcognitive.org/itmo-nss-team/FEDOT.git'
        secrets:
          GITLAB_USER: ${{ secrets.GITLAB_USER }}
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        if: ${{ steps.mirror-2.outcome == 'failure' }}
