name: Mirror repo to GitLab

on: [push, delete]

jobs:
  call-nss-ops-mirror-workflow:
    uses: ITMO-NSS-team/NSS-Ops/.github/workflows/mirror-repo.yml@2f08ee2ce9bb5cf9bd9eaeabcb98b48effdbd941
    with:
      GITLAB_URL: 'https://gitlab.actcognitive.org/itmo-nss-team/FEDOT.git'
    secrets:
      GITLAB_USER: ${{ secrets.GITLAB_USER }}
      GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
      
