name: Telegram PR merge notification
on:
  pull_request:
    types: [closed]

jobs:
  merge_job:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: send custom message with args
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            ${{ github.event.repository.name }}: the PR [#${{ github.event.number }}](${{ github.event.pull_request.html_url }}) *"${{ github.event.pull_request.title }}"* was merged.

            Description:
            ```markdown
            ${{ github.event.pull_request.body }}
            ```

            Check it out to keep your local repository updated!
