# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
    branches: [ master, release ]
  pull_request:
    branches: [ master, release ]
  workflow_dispatch:  # manually launch from GitHub actions

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        python-version: [ '3.10' ]

    steps:
    - name: Free disk space
      run: |
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc

    - name: Checkout
      uses: actions/checkout@v5

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "latest"
        enable-cache: true

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python pin ${{ matrix.python-version }}

    - name: Lock & Sync dependencies
      run: |
        uv sync --extra extra --extra examples --group profilers --dev

    - name: FEDOT core tests
      run: |
        uv run pytest test/unit --cov=fedot -s

    - name: Industrial tests
      run: |
        uv sync --extra industrial --no-dev
        cd test/industrial
        uv run pytest unit --cov=fedot_ind -s

    - name: Upload coverage
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
